# template for "Guess the number" mini-project
# input will come from buttons and an input field
# all output for the game will be printed in the console

# importing modules needed for this program

import random

import math

import simplegui



# initialize default state of this program by assigning global variables

  # initial secret numbers of the program
 

secret_num = 0
    
  #default number range once the program is run


num_range = 100

  # default remaining guesses for player before the game terminates
    
guesses_remain = 7




# helper function to start and restart the game
def new_game():
    
    #global declaration as there're global variables being modified.
    
    global secret_num, guesses_remain
    
    #number of guesses allowed for the new game
    
    guesses_remain = guesses_allowed(num_range)
    
    #Annoucing new game, along with number range and number of remaining guesses.
    
    print "New game. Range is from 0 to " + str(num_range)
    
    print "Number of remaining guesses is " + str(guesses_remain)
    
    #blank line for readability
    
    print ""
    
    
    # generating random secret number by program for every new game
      
     # for range 0 ~ 100
        
    if num_range == 100:
        
        secret_num = random.randrange(0, 100)
     
     # for range 0 ~ 1000
    
    elif num_range == 1000:
        
        secret_num = random.randrange(0, 1000)

        
        
        
# helper function to determines how many guesses are 
# allowed according to the range of the game

def guesses_allowed(num_range):
    
    global guesses_remain
    
    guesses_remain = int(math.ceil(math.log(num_range + 1, 2)))
    
    return guesses_remain
                               
   
    
# define event handlers for control panel

def range100():
    # button that changes range to range [0,100) and restarts
      
      # global declaration
        
        global num_range, guesses_remain
        
        #change the number range
    
        num_range = 100
        
        #compute the guesses allowed for player according to the range
        
        guesses_remain = guesses_allowed(num_range)
    
        # call the new_game function to restart the game when button is pressed
    
        new_game()
    


    

def range1000():
    # button that changes range to range [0,1000) and restarts
    
     # global declaration
        
        global num_range, guesses_remain
        
     #change the number range
        
        num_range = 1000
        
     #compute the guesses allowed for player according to the range
        
        guesses_remain = guesses_allowed(num_range)
        
     # call the new_game function to restart the game when button is pressed
        
        new_game()
        


    
def input_guess(guess):
    # main game logic goes here
    
     #global declaration
        
     global secret_num, guesses_remain
     
     #annoucing player guess
        
     print "Guess was " + guess
        
    
     #convert player guess string to number
    
     guessed_num = int(guess)
     
     
        
        #compare player guess to the scret number generated by the program
        #then announce result and deduct the number of remaining guesses accordingly
     
            
     if guessed_num < secret_num and guesses_remain > 1:
                
        print "Higher!"
            
        guesses_remain -= 1
            
        print "Number of remaining guesses is " + str(guesses_remain)
                
        print ""
        
     elif guessed_num > secret_num and guesses_remain > 1:
            
                print "Lower!"
            
                guesses_remain -= 1
            
                print "Number of remaining guesses is " + str(guesses_remain)
                
                print ""
            
     elif guessed_num == secret_num:
            
                print "Correct!"
                
                print ""
            
                new_game()
      
     else:
                    
          print "You have ran out of guesses, the number was " + str(secret_num)
          
          print ""
                    
          new_game()
                    
    
    

    
# create frame

frame = simplegui.create_frame("Guess the number!", 100, 150)

# creat a input box

inp = frame.add_input("Guess your number :)", input_guess, 50)


# register event handlers for control elements

button_100 = frame.add_button("range100", range100, 100)

button_1000 = frame.add_button("range1000", range1000, 100)



# call new_game and start frame

new_game()

frame.start



# always remember to check your completed program against the grading rubric

###comment by ashu774

#def guesses_allowed(num_range) :D extemely smart code to deduce allowed number of guessing ... i am impressed.. you will
#do well in the 6.001x course :). 

#its time you learn string formatting in python .. you can use codeacademy (may be chapter 2) .. it will help you writing
#complex strings later :)

#plausible, well commented code .. good :)

